### ISSUE TITLE
How to implement spatial attention module?

### ISSUE THREAD

**Issue by imyangs** [Christian-lyc/NAM#1]
Dear author

Do you have any plans to relase the code for spatial attention? If not, please give some ideas about how to implement. 
Many thanks.

**Comment by Christian-lyc** [comment]
Hi, thank you so much for your interest. 
The spatial part is same as the channel part. you basically need to reshape the H and W to 1 D. BN just measure the importance of each pixel.

**Comment by imyangs** [comment]
Hi, so many thanks for your quick reply.

As I cannot map the default dimension of scale factor of BN to spatial dims ( C != H X W ? ), so my real concern is how to implement the "pixel normalization" module.  My idea is set "self.channels = HxW", and than the forward() func should implement as below:

please help me figure out the right soultion. Many thanks.

![image](https://user-images.githubusercontent.com/28534716/144550907-2b518571-10e1-4926-b100-8da857d5337f.png)

**Comment by Christian-lyc** [comment]
Hi, It seems this is the same as the paper said.

**Comment by imyangs** [comment]
Thank you so much. I will test it later.

**Comment by Ronky123** [comment]
> Thank you so much. I will test it later.

hi,do you test the spatial attention?does it work?

**Comment by imyangs** [comment]
> > Thank you so much. I will test it later.
> 
> hi,do you test the spatial attention?does it work?

Sorry, I have not. Maybe you can just paste my above code and run the train script for a result.

**Comment by haikunzhang95** [comment]
> Thank you so much. I will test it later.

Hi, did you test your spatial attention codes? Does it work well?
Thank you!

**Comment by 23jisuper** [comment]
> > > 非常感谢。我稍后会测试它。
> > 
> > 
> > 嗨，你测试空间注意力吗？它有效吗？
> 
> 对不起，我没有。也许你可以粘贴我上面的代码并运行训练脚本以获得结果。

您好  关于空间注意力您实现了吗？  我的想法是能不能先采用池化将H*W进行归一化  在计算BN
