### ISSUE TITLE
what is the meaning of expanding ratio，I don't understand it

### ISSUE THREAD

**Issue by yuan-kai-design** [Christian-lyc/NAM#10]
![PKAJ2307)@W$EZETPSGG8`D](https://user-images.githubusercontent.com/78480103/200174771-f8a3be79-5b9c-4e4c-9f3c-152ef55344d6.png)

**Comment by Christian-lyc** [comment]
Hi, thank you for your interesting. I think you can find it in the original BAM and CBAM code.
